### ISSUE TITLE
Capacity type is different to that of COBREXA

### ISSUE THREAD

**Issue by HettieC** [stelmo/DifferentiableMetabolism.jl#13]
Hello!

Only a small issue, but adds one unnecessary line of code to change the type: the function ```build_kinetic_model()``` requires a ```capacity``` with ```Real``` values, but in the COBREXA function ```enzyme_constrained_flux_balance_analysis()``` you have essentially the same variable but with ```Float64``` values.

Would be nice if they both used ```Vector{Tuple{String, Vector{String}, Float64}}``` (or the same but ```Real```).

**Comment by exaexa** [comment]
oh true. @stelmo is the `Real` there because of required polymorphism (does Num get into capacities?) or can we just use Float64 everytime?

**Comment by exaexa** [comment]
aok wait the conversion is actually hampered by forcibly storing a polymorphic Real box in a parameter container. I added a possible fix to #14
